#!/bin/bash

# exit if any error from a 'simple command'
set -o errexit

export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

# use .config file or pass arguments; arguments win if both
[[ -r .config ]] && source .config
readonly OWNER="${4:-$OWNER}"
readonly REPO="${5:-$REPO}"
readonly REPO_PATH="${6:-$REPO_PATH}"
readonly API_USER="${7:-$API_USER}"
readonly API_KEY="${8:-$API_KEY}"
readonly SHASUM_ALG="${9:-$SHASUM_ALG}"
readonly KNOWN_HASH="${10:-$KNOWN_HASH}"
readonly REPO_BRANCH="${11:-$REPO_BRANCH}"

function error() {
  echo "[$(date '+%FT%T%z')] ERROR: $*" >&2
}

function output() {
  echo "[$(date '+%FT%T%z')] OUTPUT: $*"
}

function confirm_dependencies() {
  # really for jq but why not check them all while we're at it
  dependencies=(
    echo
    curl
    shasum
    jq
    base64
    awk
  )
  for dep in "${dependencies[@]}"; do
    if ! which -s "$dep"; then
      error "dependency '$dep' missing; exiting"
      exit 1
    fi
  done
}

function get_script_content() {
  response="$(
    curl \
      --silent \
      --show-error \
      --fail \
      --tlsv1.2 \
      --header "Accept: application/vnd.github.v3+json" \
      --get --data-urlencode "ref=$REPO_BRANCH" \
      --user "$API_USER:$API_KEY" \
      "https://api.github.com/repos/$OWNER/$REPO/contents/$REPO_PATH" |
      jq --raw-output .content |
      base64 --decode
  )"
}

function validate() {
  response_hash="$(
    echo "$response" |
      shasum -a "$SHASUM_ALGORITHM" |
      awk '{print $1}'
  )"
  if [[ "$response_hash" == "$KNOWN_HASH" ]]; then
    output "Hash Match - Download validated"
  else
    error "Hash Mismatch - Download failed validation"
    exit 1
  fi
}

function main() {
  confirm_dependencies
  get_script_content
  validate
}

main
